version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_2102_AWSINT_2Project
  gitServerName: SIQA_kvv_ibm
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_2102_awsint_2.integrations:Sum
  packages:
  - name: SIQA_2102_AWSINT_2Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2033
